### ISSUE TITLE
BIOS submodule URL uses SSH, rather than HTTPS

### ISSUE THREAD

**Issue by ktemkin** [lambdaconcept/lambdasoc#1]
Currently, the BIOS submodule is referenced as an SSH address:

```
[submodule "lambdasoc/software/bios"]
	path = lambdasoc/software/bios
	url = git@github.com:lambdaconcept/lambdasoc-bios
```

This means that the submodule can only be pulled down if a GitHub-associated SSH key is available; which is somewhat stymieing when using `lambdasoc` in CI environments.

Would it be possible to change this to HTTPS? I'd happy submit a PR. :)

**Comment by jfng** [comment]
Thanks! I forgot to update it when we published the repo.
