### ISSUE TITLE
pip install takes to long

### ISSUE THREAD

**Issue by andresdemski** [lambdaconcept/lambdasoc#12]
When I install lambdasoc with pip, It takes too long because it clones submodules recursively, cloning the llvm project which is huge.

Some possible solutions:
* Download bios files from its repository when labdasoc is installed or during building process of an soc.
* Remove llvm-project from the bios repository
* Use another way to track llvm-project. Maybe cloning it in the Makefile

Regards.

**Comment by jfng** [comment]
Sorry for the delay. I fixed this (once and for all, hopefully) by copying the required builtins to the lambdasoc-bios repo.
